version: '3.8'

services:
  api:
    image: wstool-be-2
    container_name: aspnet_api
    ports:
      - "5000:8080"  # Map port 5000 (host) -> 8080 (container)
    networks:
      - wstool-network-2

  ui:
    image: wstool-fe-2
    container_name: angular_ui
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - wstool-network-2

networks:
  wstool-network-2:
    driver: bridge
