networks:
  wstool_webnet_2:
    external: true 
    
services:
  wstool-be-2:
    image: wstool-be-2
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: wstool_be_2
    ports:
      - "5000:8080"
    networks:
      - wstool_webnet_2
    user: "0:0"

  wstool-fe-2:
    image: wstool-fe-2
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: wstool_fe_2
    ports:
      - "4200:80"
    depends_on:
      - wstool-be-2
    networks:
      - wstool_webnet_2
